package muni

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"fmt"

	"github.com/carlosruizg/muni/ent"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Experts is the resolver for the experts field.
func (r *queryResolver) Experts(ctx context.Context) ([]*ent.Expert, error) {
	return r.client.Expert.Query().All(ctx)
}

// LabellingTasks is the resolver for the labellingTasks field.
func (r *queryResolver) LabellingTasks(ctx context.Context) ([]*ent.LabellingTask, error) {
	panic(fmt.Errorf("not implemented: LabellingTasks - labellingTasks"))
}

// LabellingTaskResponses is the resolver for the labellingTaskResponses field.
func (r *queryResolver) LabellingTaskResponses(ctx context.Context) ([]*ent.LabellingTaskResponse, error) {
	panic(fmt.Errorf("not implemented: LabellingTaskResponses - labellingTaskResponses"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
