// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/carlosruizg/muni/ent/expert"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// ExpertEdge is the edge representation of Expert.
type ExpertEdge struct {
	Node   *Expert `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

// ExpertConnection is the connection containing edges to Expert.
type ExpertConnection struct {
	Edges      []*ExpertEdge `json:"edges"`
	PageInfo   PageInfo      `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

func (c *ExpertConnection) build(nodes []*Expert, pager *expertPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Expert
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Expert {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Expert {
			return nodes[i]
		}
	}
	c.Edges = make([]*ExpertEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &ExpertEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// ExpertPaginateOption enables pagination customization.
type ExpertPaginateOption func(*expertPager) error

// WithExpertOrder configures pagination ordering.
func WithExpertOrder(order *ExpertOrder) ExpertPaginateOption {
	if order == nil {
		order = DefaultExpertOrder
	}
	o := *order
	return func(pager *expertPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultExpertOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithExpertFilter configures pagination filter.
func WithExpertFilter(filter func(*ExpertQuery) (*ExpertQuery, error)) ExpertPaginateOption {
	return func(pager *expertPager) error {
		if filter == nil {
			return errors.New("ExpertQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type expertPager struct {
	reverse bool
	order   *ExpertOrder
	filter  func(*ExpertQuery) (*ExpertQuery, error)
}

func newExpertPager(opts []ExpertPaginateOption, reverse bool) (*expertPager, error) {
	pager := &expertPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultExpertOrder
	}
	return pager, nil
}

func (p *expertPager) applyFilter(query *ExpertQuery) (*ExpertQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *expertPager) toCursor(e *Expert) Cursor {
	return p.order.Field.toCursor(e)
}

func (p *expertPager) applyCursors(query *ExpertQuery, after, before *Cursor) (*ExpertQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultExpertOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *expertPager) applyOrder(query *ExpertQuery) *ExpertQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultExpertOrder.Field {
		query = query.Order(DefaultExpertOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *expertPager) orderExpr(query *ExpertQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultExpertOrder.Field {
			b.Comma().Ident(DefaultExpertOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Expert.
func (e *ExpertQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...ExpertPaginateOption,
) (*ExpertConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newExpertPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if e, err = pager.applyFilter(e); err != nil {
		return nil, err
	}
	conn := &ExpertConnection{Edges: []*ExpertEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := e.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if e, err = pager.applyCursors(e, after, before); err != nil {
		return nil, err
	}
	if limit := paginateLimit(first, last); limit != 0 {
		e.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := e.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	e = pager.applyOrder(e)
	nodes, err := e.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// ExpertOrderField defines the ordering field of Expert.
type ExpertOrderField struct {
	// Value extracts the ordering value from the given Expert.
	Value    func(*Expert) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) expert.OrderOption
	toCursor func(*Expert) Cursor
}

// ExpertOrder defines the ordering of Expert.
type ExpertOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     *ExpertOrderField `json:"field"`
}

// DefaultExpertOrder is the default ordering of Expert.
var DefaultExpertOrder = &ExpertOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &ExpertOrderField{
		Value: func(e *Expert) (ent.Value, error) {
			return e.ID, nil
		},
		column: expert.FieldID,
		toTerm: expert.ByID,
		toCursor: func(e *Expert) Cursor {
			return Cursor{ID: e.ID}
		},
	},
}

// ToEdge converts Expert into ExpertEdge.
func (e *Expert) ToEdge(order *ExpertOrder) *ExpertEdge {
	if order == nil {
		order = DefaultExpertOrder
	}
	return &ExpertEdge{
		Node:   e,
		Cursor: order.Field.toCursor(e),
	}
}
