// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (e *Expert) Qualifications(ctx context.Context) (result []*Qualification, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = e.NamedQualifications(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = e.Edges.QualificationsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = e.QueryQualifications().All(ctx)
	}
	return result, err
}

func (q *Qualification) Experts(ctx context.Context) (result []*Expert, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = q.NamedExperts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = q.Edges.ExpertsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = q.QueryExperts().All(ctx)
	}
	return result, err
}
