// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/carlosruizg/muni/ent/labellingproject"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// LabellingProjectEdge is the edge representation of LabellingProject.
type LabellingProjectEdge struct {
	Node   *LabellingProject `json:"node"`
	Cursor Cursor            `json:"cursor"`
}

// LabellingProjectConnection is the connection containing edges to LabellingProject.
type LabellingProjectConnection struct {
	Edges      []*LabellingProjectEdge `json:"edges"`
	PageInfo   PageInfo                `json:"pageInfo"`
	TotalCount int                     `json:"totalCount"`
}

func (c *LabellingProjectConnection) build(nodes []*LabellingProject, pager *labellingprojectPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *LabellingProject
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *LabellingProject {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *LabellingProject {
			return nodes[i]
		}
	}
	c.Edges = make([]*LabellingProjectEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &LabellingProjectEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// LabellingProjectPaginateOption enables pagination customization.
type LabellingProjectPaginateOption func(*labellingprojectPager) error

// WithLabellingProjectOrder configures pagination ordering.
func WithLabellingProjectOrder(order *LabellingProjectOrder) LabellingProjectPaginateOption {
	if order == nil {
		order = DefaultLabellingProjectOrder
	}
	o := *order
	return func(pager *labellingprojectPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultLabellingProjectOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithLabellingProjectFilter configures pagination filter.
func WithLabellingProjectFilter(filter func(*LabellingProjectQuery) (*LabellingProjectQuery, error)) LabellingProjectPaginateOption {
	return func(pager *labellingprojectPager) error {
		if filter == nil {
			return errors.New("LabellingProjectQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type labellingprojectPager struct {
	reverse bool
	order   *LabellingProjectOrder
	filter  func(*LabellingProjectQuery) (*LabellingProjectQuery, error)
}

func newLabellingProjectPager(opts []LabellingProjectPaginateOption, reverse bool) (*labellingprojectPager, error) {
	pager := &labellingprojectPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultLabellingProjectOrder
	}
	return pager, nil
}

func (p *labellingprojectPager) applyFilter(query *LabellingProjectQuery) (*LabellingProjectQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *labellingprojectPager) toCursor(lp *LabellingProject) Cursor {
	return p.order.Field.toCursor(lp)
}

func (p *labellingprojectPager) applyCursors(query *LabellingProjectQuery, after, before *Cursor) (*LabellingProjectQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultLabellingProjectOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *labellingprojectPager) applyOrder(query *LabellingProjectQuery) *LabellingProjectQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultLabellingProjectOrder.Field {
		query = query.Order(DefaultLabellingProjectOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *labellingprojectPager) orderExpr(query *LabellingProjectQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultLabellingProjectOrder.Field {
			b.Comma().Ident(DefaultLabellingProjectOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to LabellingProject.
func (lp *LabellingProjectQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...LabellingProjectPaginateOption,
) (*LabellingProjectConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newLabellingProjectPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if lp, err = pager.applyFilter(lp); err != nil {
		return nil, err
	}
	conn := &LabellingProjectConnection{Edges: []*LabellingProjectEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := lp.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if lp, err = pager.applyCursors(lp, after, before); err != nil {
		return nil, err
	}
	if limit := paginateLimit(first, last); limit != 0 {
		lp.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := lp.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	lp = pager.applyOrder(lp)
	nodes, err := lp.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// LabellingProjectOrderField defines the ordering field of LabellingProject.
type LabellingProjectOrderField struct {
	// Value extracts the ordering value from the given LabellingProject.
	Value    func(*LabellingProject) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) labellingproject.OrderOption
	toCursor func(*LabellingProject) Cursor
}

// LabellingProjectOrder defines the ordering of LabellingProject.
type LabellingProjectOrder struct {
	Direction OrderDirection              `json:"direction"`
	Field     *LabellingProjectOrderField `json:"field"`
}

// DefaultLabellingProjectOrder is the default ordering of LabellingProject.
var DefaultLabellingProjectOrder = &LabellingProjectOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &LabellingProjectOrderField{
		Value: func(lp *LabellingProject) (ent.Value, error) {
			return lp.ID, nil
		},
		column: labellingproject.FieldID,
		toTerm: labellingproject.ByID,
		toCursor: func(lp *LabellingProject) Cursor {
			return Cursor{ID: lp.ID}
		},
	},
}

// ToEdge converts LabellingProject into LabellingProjectEdge.
func (lp *LabellingProject) ToEdge(order *LabellingProjectOrder) *LabellingProjectEdge {
	if order == nil {
		order = DefaultLabellingProjectOrder
	}
	return &LabellingProjectEdge{
		Node:   lp,
		Cursor: order.Field.toCursor(lp),
	}
}
