// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/carlosruizg/muni/ent/labellingtaskresponse"
	"github.com/carlosruizg/muni/ent/predicate"
)

// LabellingTaskResponseDelete is the builder for deleting a LabellingTaskResponse entity.
type LabellingTaskResponseDelete struct {
	config
	hooks    []Hook
	mutation *LabellingTaskResponseMutation
}

// Where appends a list predicates to the LabellingTaskResponseDelete builder.
func (ltrd *LabellingTaskResponseDelete) Where(ps ...predicate.LabellingTaskResponse) *LabellingTaskResponseDelete {
	ltrd.mutation.Where(ps...)
	return ltrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ltrd *LabellingTaskResponseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ltrd.sqlExec, ltrd.mutation, ltrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ltrd *LabellingTaskResponseDelete) ExecX(ctx context.Context) int {
	n, err := ltrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ltrd *LabellingTaskResponseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(labellingtaskresponse.Table, sqlgraph.NewFieldSpec(labellingtaskresponse.FieldID, field.TypeInt))
	if ps := ltrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ltrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ltrd.mutation.done = true
	return affected, err
}

// LabellingTaskResponseDeleteOne is the builder for deleting a single LabellingTaskResponse entity.
type LabellingTaskResponseDeleteOne struct {
	ltrd *LabellingTaskResponseDelete
}

// Where appends a list predicates to the LabellingTaskResponseDelete builder.
func (ltrdo *LabellingTaskResponseDeleteOne) Where(ps ...predicate.LabellingTaskResponse) *LabellingTaskResponseDeleteOne {
	ltrdo.ltrd.mutation.Where(ps...)
	return ltrdo
}

// Exec executes the deletion query.
func (ltrdo *LabellingTaskResponseDeleteOne) Exec(ctx context.Context) error {
	n, err := ltrdo.ltrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{labellingtaskresponse.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ltrdo *LabellingTaskResponseDeleteOne) ExecX(ctx context.Context) {
	if err := ltrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
