// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/carlosruizg/muni/ent/expert"
	"github.com/carlosruizg/muni/ent/labellingproject"
	"github.com/carlosruizg/muni/ent/labellingtask"
	"github.com/carlosruizg/muni/ent/labellingtaskresponse"
	"github.com/carlosruizg/muni/ent/predicate"
	"github.com/carlosruizg/muni/ent/qualification"
	"github.com/carlosruizg/muni/enums"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeExpert                = "Expert"
	TypeLabellingProject      = "LabellingProject"
	TypeLabellingTask         = "LabellingTask"
	TypeLabellingTaskResponse = "LabellingTaskResponse"
	TypeQualification         = "Qualification"
)

// ExpertMutation represents an operation that mutates the Expert nodes in the graph.
type ExpertMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int
	name                  *string
	clearedFields         map[string]struct{}
	qualifications        map[int]struct{}
	removedqualifications map[int]struct{}
	clearedqualifications bool
	done                  bool
	oldValue              func(context.Context) (*Expert, error)
	predicates            []predicate.Expert
}

var _ ent.Mutation = (*ExpertMutation)(nil)

// expertOption allows management of the mutation configuration using functional options.
type expertOption func(*ExpertMutation)

// newExpertMutation creates new mutation for the Expert entity.
func newExpertMutation(c config, op Op, opts ...expertOption) *ExpertMutation {
	m := &ExpertMutation{
		config:        c,
		op:            op,
		typ:           TypeExpert,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withExpertID sets the ID field of the mutation.
func withExpertID(id int) expertOption {
	return func(m *ExpertMutation) {
		var (
			err   error
			once  sync.Once
			value *Expert
		)
		m.oldValue = func(ctx context.Context) (*Expert, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Expert.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withExpert sets the old Expert of the mutation.
func withExpert(node *Expert) expertOption {
	return func(m *ExpertMutation) {
		m.oldValue = func(context.Context) (*Expert, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ExpertMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ExpertMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ExpertMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ExpertMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Expert.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ExpertMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ExpertMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Expert entity.
// If the Expert object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExpertMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ExpertMutation) ResetName() {
	m.name = nil
}

// AddQualificationIDs adds the "qualifications" edge to the Qualification entity by ids.
func (m *ExpertMutation) AddQualificationIDs(ids ...int) {
	if m.qualifications == nil {
		m.qualifications = make(map[int]struct{})
	}
	for i := range ids {
		m.qualifications[ids[i]] = struct{}{}
	}
}

// ClearQualifications clears the "qualifications" edge to the Qualification entity.
func (m *ExpertMutation) ClearQualifications() {
	m.clearedqualifications = true
}

// QualificationsCleared reports if the "qualifications" edge to the Qualification entity was cleared.
func (m *ExpertMutation) QualificationsCleared() bool {
	return m.clearedqualifications
}

// RemoveQualificationIDs removes the "qualifications" edge to the Qualification entity by IDs.
func (m *ExpertMutation) RemoveQualificationIDs(ids ...int) {
	if m.removedqualifications == nil {
		m.removedqualifications = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.qualifications, ids[i])
		m.removedqualifications[ids[i]] = struct{}{}
	}
}

// RemovedQualifications returns the removed IDs of the "qualifications" edge to the Qualification entity.
func (m *ExpertMutation) RemovedQualificationsIDs() (ids []int) {
	for id := range m.removedqualifications {
		ids = append(ids, id)
	}
	return
}

// QualificationsIDs returns the "qualifications" edge IDs in the mutation.
func (m *ExpertMutation) QualificationsIDs() (ids []int) {
	for id := range m.qualifications {
		ids = append(ids, id)
	}
	return
}

// ResetQualifications resets all changes to the "qualifications" edge.
func (m *ExpertMutation) ResetQualifications() {
	m.qualifications = nil
	m.clearedqualifications = false
	m.removedqualifications = nil
}

// Where appends a list predicates to the ExpertMutation builder.
func (m *ExpertMutation) Where(ps ...predicate.Expert) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ExpertMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ExpertMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Expert, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ExpertMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ExpertMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Expert).
func (m *ExpertMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ExpertMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, expert.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ExpertMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case expert.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ExpertMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case expert.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Expert field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ExpertMutation) SetField(name string, value ent.Value) error {
	switch name {
	case expert.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Expert field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ExpertMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ExpertMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ExpertMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Expert numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ExpertMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ExpertMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ExpertMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Expert nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ExpertMutation) ResetField(name string) error {
	switch name {
	case expert.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Expert field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ExpertMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.qualifications != nil {
		edges = append(edges, expert.EdgeQualifications)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ExpertMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case expert.EdgeQualifications:
		ids := make([]ent.Value, 0, len(m.qualifications))
		for id := range m.qualifications {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ExpertMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedqualifications != nil {
		edges = append(edges, expert.EdgeQualifications)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ExpertMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case expert.EdgeQualifications:
		ids := make([]ent.Value, 0, len(m.removedqualifications))
		for id := range m.removedqualifications {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ExpertMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedqualifications {
		edges = append(edges, expert.EdgeQualifications)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ExpertMutation) EdgeCleared(name string) bool {
	switch name {
	case expert.EdgeQualifications:
		return m.clearedqualifications
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ExpertMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Expert unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ExpertMutation) ResetEdge(name string) error {
	switch name {
	case expert.EdgeQualifications:
		m.ResetQualifications()
		return nil
	}
	return fmt.Errorf("unknown Expert edge %s", name)
}

// LabellingProjectMutation represents an operation that mutates the LabellingProject nodes in the graph.
type LabellingProjectMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	name                *string
	status              *labellingproject.Status
	description         *string
	is_private          *bool
	callback_url        *string
	workers_per_task    *int
	addworkers_per_task *int
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*LabellingProject, error)
	predicates          []predicate.LabellingProject
}

var _ ent.Mutation = (*LabellingProjectMutation)(nil)

// labellingprojectOption allows management of the mutation configuration using functional options.
type labellingprojectOption func(*LabellingProjectMutation)

// newLabellingProjectMutation creates new mutation for the LabellingProject entity.
func newLabellingProjectMutation(c config, op Op, opts ...labellingprojectOption) *LabellingProjectMutation {
	m := &LabellingProjectMutation{
		config:        c,
		op:            op,
		typ:           TypeLabellingProject,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLabellingProjectID sets the ID field of the mutation.
func withLabellingProjectID(id int) labellingprojectOption {
	return func(m *LabellingProjectMutation) {
		var (
			err   error
			once  sync.Once
			value *LabellingProject
		)
		m.oldValue = func(ctx context.Context) (*LabellingProject, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().LabellingProject.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLabellingProject sets the old LabellingProject of the mutation.
func withLabellingProject(node *LabellingProject) labellingprojectOption {
	return func(m *LabellingProjectMutation) {
		m.oldValue = func(context.Context) (*LabellingProject, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LabellingProjectMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LabellingProjectMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LabellingProjectMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LabellingProjectMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().LabellingProject.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *LabellingProjectMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *LabellingProjectMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the LabellingProject entity.
// If the LabellingProject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingProjectMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *LabellingProjectMutation) ResetName() {
	m.name = nil
}

// SetStatus sets the "status" field.
func (m *LabellingProjectMutation) SetStatus(l labellingproject.Status) {
	m.status = &l
}

// Status returns the value of the "status" field in the mutation.
func (m *LabellingProjectMutation) Status() (r labellingproject.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the LabellingProject entity.
// If the LabellingProject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingProjectMutation) OldStatus(ctx context.Context) (v labellingproject.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *LabellingProjectMutation) ResetStatus() {
	m.status = nil
}

// SetDescription sets the "description" field.
func (m *LabellingProjectMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *LabellingProjectMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the LabellingProject entity.
// If the LabellingProject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingProjectMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *LabellingProjectMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[labellingproject.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *LabellingProjectMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[labellingproject.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *LabellingProjectMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, labellingproject.FieldDescription)
}

// SetIsPrivate sets the "is_private" field.
func (m *LabellingProjectMutation) SetIsPrivate(b bool) {
	m.is_private = &b
}

// IsPrivate returns the value of the "is_private" field in the mutation.
func (m *LabellingProjectMutation) IsPrivate() (r bool, exists bool) {
	v := m.is_private
	if v == nil {
		return
	}
	return *v, true
}

// OldIsPrivate returns the old "is_private" field's value of the LabellingProject entity.
// If the LabellingProject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingProjectMutation) OldIsPrivate(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsPrivate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsPrivate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsPrivate: %w", err)
	}
	return oldValue.IsPrivate, nil
}

// ResetIsPrivate resets all changes to the "is_private" field.
func (m *LabellingProjectMutation) ResetIsPrivate() {
	m.is_private = nil
}

// SetCallbackURL sets the "callback_url" field.
func (m *LabellingProjectMutation) SetCallbackURL(s string) {
	m.callback_url = &s
}

// CallbackURL returns the value of the "callback_url" field in the mutation.
func (m *LabellingProjectMutation) CallbackURL() (r string, exists bool) {
	v := m.callback_url
	if v == nil {
		return
	}
	return *v, true
}

// OldCallbackURL returns the old "callback_url" field's value of the LabellingProject entity.
// If the LabellingProject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingProjectMutation) OldCallbackURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCallbackURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCallbackURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCallbackURL: %w", err)
	}
	return oldValue.CallbackURL, nil
}

// ClearCallbackURL clears the value of the "callback_url" field.
func (m *LabellingProjectMutation) ClearCallbackURL() {
	m.callback_url = nil
	m.clearedFields[labellingproject.FieldCallbackURL] = struct{}{}
}

// CallbackURLCleared returns if the "callback_url" field was cleared in this mutation.
func (m *LabellingProjectMutation) CallbackURLCleared() bool {
	_, ok := m.clearedFields[labellingproject.FieldCallbackURL]
	return ok
}

// ResetCallbackURL resets all changes to the "callback_url" field.
func (m *LabellingProjectMutation) ResetCallbackURL() {
	m.callback_url = nil
	delete(m.clearedFields, labellingproject.FieldCallbackURL)
}

// SetWorkersPerTask sets the "workers_per_task" field.
func (m *LabellingProjectMutation) SetWorkersPerTask(i int) {
	m.workers_per_task = &i
	m.addworkers_per_task = nil
}

// WorkersPerTask returns the value of the "workers_per_task" field in the mutation.
func (m *LabellingProjectMutation) WorkersPerTask() (r int, exists bool) {
	v := m.workers_per_task
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkersPerTask returns the old "workers_per_task" field's value of the LabellingProject entity.
// If the LabellingProject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingProjectMutation) OldWorkersPerTask(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkersPerTask is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkersPerTask requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkersPerTask: %w", err)
	}
	return oldValue.WorkersPerTask, nil
}

// AddWorkersPerTask adds i to the "workers_per_task" field.
func (m *LabellingProjectMutation) AddWorkersPerTask(i int) {
	if m.addworkers_per_task != nil {
		*m.addworkers_per_task += i
	} else {
		m.addworkers_per_task = &i
	}
}

// AddedWorkersPerTask returns the value that was added to the "workers_per_task" field in this mutation.
func (m *LabellingProjectMutation) AddedWorkersPerTask() (r int, exists bool) {
	v := m.addworkers_per_task
	if v == nil {
		return
	}
	return *v, true
}

// ResetWorkersPerTask resets all changes to the "workers_per_task" field.
func (m *LabellingProjectMutation) ResetWorkersPerTask() {
	m.workers_per_task = nil
	m.addworkers_per_task = nil
}

// Where appends a list predicates to the LabellingProjectMutation builder.
func (m *LabellingProjectMutation) Where(ps ...predicate.LabellingProject) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LabellingProjectMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LabellingProjectMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.LabellingProject, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LabellingProjectMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LabellingProjectMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (LabellingProject).
func (m *LabellingProjectMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LabellingProjectMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, labellingproject.FieldName)
	}
	if m.status != nil {
		fields = append(fields, labellingproject.FieldStatus)
	}
	if m.description != nil {
		fields = append(fields, labellingproject.FieldDescription)
	}
	if m.is_private != nil {
		fields = append(fields, labellingproject.FieldIsPrivate)
	}
	if m.callback_url != nil {
		fields = append(fields, labellingproject.FieldCallbackURL)
	}
	if m.workers_per_task != nil {
		fields = append(fields, labellingproject.FieldWorkersPerTask)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LabellingProjectMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case labellingproject.FieldName:
		return m.Name()
	case labellingproject.FieldStatus:
		return m.Status()
	case labellingproject.FieldDescription:
		return m.Description()
	case labellingproject.FieldIsPrivate:
		return m.IsPrivate()
	case labellingproject.FieldCallbackURL:
		return m.CallbackURL()
	case labellingproject.FieldWorkersPerTask:
		return m.WorkersPerTask()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LabellingProjectMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case labellingproject.FieldName:
		return m.OldName(ctx)
	case labellingproject.FieldStatus:
		return m.OldStatus(ctx)
	case labellingproject.FieldDescription:
		return m.OldDescription(ctx)
	case labellingproject.FieldIsPrivate:
		return m.OldIsPrivate(ctx)
	case labellingproject.FieldCallbackURL:
		return m.OldCallbackURL(ctx)
	case labellingproject.FieldWorkersPerTask:
		return m.OldWorkersPerTask(ctx)
	}
	return nil, fmt.Errorf("unknown LabellingProject field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabellingProjectMutation) SetField(name string, value ent.Value) error {
	switch name {
	case labellingproject.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case labellingproject.FieldStatus:
		v, ok := value.(labellingproject.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case labellingproject.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case labellingproject.FieldIsPrivate:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsPrivate(v)
		return nil
	case labellingproject.FieldCallbackURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCallbackURL(v)
		return nil
	case labellingproject.FieldWorkersPerTask:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkersPerTask(v)
		return nil
	}
	return fmt.Errorf("unknown LabellingProject field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LabellingProjectMutation) AddedFields() []string {
	var fields []string
	if m.addworkers_per_task != nil {
		fields = append(fields, labellingproject.FieldWorkersPerTask)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LabellingProjectMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case labellingproject.FieldWorkersPerTask:
		return m.AddedWorkersPerTask()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabellingProjectMutation) AddField(name string, value ent.Value) error {
	switch name {
	case labellingproject.FieldWorkersPerTask:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddWorkersPerTask(v)
		return nil
	}
	return fmt.Errorf("unknown LabellingProject numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LabellingProjectMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(labellingproject.FieldDescription) {
		fields = append(fields, labellingproject.FieldDescription)
	}
	if m.FieldCleared(labellingproject.FieldCallbackURL) {
		fields = append(fields, labellingproject.FieldCallbackURL)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LabellingProjectMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LabellingProjectMutation) ClearField(name string) error {
	switch name {
	case labellingproject.FieldDescription:
		m.ClearDescription()
		return nil
	case labellingproject.FieldCallbackURL:
		m.ClearCallbackURL()
		return nil
	}
	return fmt.Errorf("unknown LabellingProject nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LabellingProjectMutation) ResetField(name string) error {
	switch name {
	case labellingproject.FieldName:
		m.ResetName()
		return nil
	case labellingproject.FieldStatus:
		m.ResetStatus()
		return nil
	case labellingproject.FieldDescription:
		m.ResetDescription()
		return nil
	case labellingproject.FieldIsPrivate:
		m.ResetIsPrivate()
		return nil
	case labellingproject.FieldCallbackURL:
		m.ResetCallbackURL()
		return nil
	case labellingproject.FieldWorkersPerTask:
		m.ResetWorkersPerTask()
		return nil
	}
	return fmt.Errorf("unknown LabellingProject field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LabellingProjectMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LabellingProjectMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LabellingProjectMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LabellingProjectMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LabellingProjectMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LabellingProjectMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LabellingProjectMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown LabellingProject unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LabellingProjectMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown LabellingProject edge %s", name)
}

// LabellingTaskMutation represents an operation that mutates the LabellingTask nodes in the graph.
type LabellingTaskMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	description   *string
	instructions  *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*LabellingTask, error)
	predicates    []predicate.LabellingTask
}

var _ ent.Mutation = (*LabellingTaskMutation)(nil)

// labellingtaskOption allows management of the mutation configuration using functional options.
type labellingtaskOption func(*LabellingTaskMutation)

// newLabellingTaskMutation creates new mutation for the LabellingTask entity.
func newLabellingTaskMutation(c config, op Op, opts ...labellingtaskOption) *LabellingTaskMutation {
	m := &LabellingTaskMutation{
		config:        c,
		op:            op,
		typ:           TypeLabellingTask,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLabellingTaskID sets the ID field of the mutation.
func withLabellingTaskID(id int) labellingtaskOption {
	return func(m *LabellingTaskMutation) {
		var (
			err   error
			once  sync.Once
			value *LabellingTask
		)
		m.oldValue = func(ctx context.Context) (*LabellingTask, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().LabellingTask.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLabellingTask sets the old LabellingTask of the mutation.
func withLabellingTask(node *LabellingTask) labellingtaskOption {
	return func(m *LabellingTaskMutation) {
		m.oldValue = func(context.Context) (*LabellingTask, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LabellingTaskMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LabellingTaskMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LabellingTaskMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LabellingTaskMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().LabellingTask.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *LabellingTaskMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *LabellingTaskMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the LabellingTask entity.
// If the LabellingTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingTaskMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *LabellingTaskMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *LabellingTaskMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *LabellingTaskMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the LabellingTask entity.
// If the LabellingTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingTaskMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *LabellingTaskMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[labellingtask.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *LabellingTaskMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[labellingtask.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *LabellingTaskMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, labellingtask.FieldDescription)
}

// SetInstructions sets the "instructions" field.
func (m *LabellingTaskMutation) SetInstructions(s string) {
	m.instructions = &s
}

// Instructions returns the value of the "instructions" field in the mutation.
func (m *LabellingTaskMutation) Instructions() (r string, exists bool) {
	v := m.instructions
	if v == nil {
		return
	}
	return *v, true
}

// OldInstructions returns the old "instructions" field's value of the LabellingTask entity.
// If the LabellingTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingTaskMutation) OldInstructions(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstructions is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstructions requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstructions: %w", err)
	}
	return oldValue.Instructions, nil
}

// ResetInstructions resets all changes to the "instructions" field.
func (m *LabellingTaskMutation) ResetInstructions() {
	m.instructions = nil
}

// Where appends a list predicates to the LabellingTaskMutation builder.
func (m *LabellingTaskMutation) Where(ps ...predicate.LabellingTask) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LabellingTaskMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LabellingTaskMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.LabellingTask, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LabellingTaskMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LabellingTaskMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (LabellingTask).
func (m *LabellingTaskMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LabellingTaskMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, labellingtask.FieldName)
	}
	if m.description != nil {
		fields = append(fields, labellingtask.FieldDescription)
	}
	if m.instructions != nil {
		fields = append(fields, labellingtask.FieldInstructions)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LabellingTaskMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case labellingtask.FieldName:
		return m.Name()
	case labellingtask.FieldDescription:
		return m.Description()
	case labellingtask.FieldInstructions:
		return m.Instructions()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LabellingTaskMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case labellingtask.FieldName:
		return m.OldName(ctx)
	case labellingtask.FieldDescription:
		return m.OldDescription(ctx)
	case labellingtask.FieldInstructions:
		return m.OldInstructions(ctx)
	}
	return nil, fmt.Errorf("unknown LabellingTask field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabellingTaskMutation) SetField(name string, value ent.Value) error {
	switch name {
	case labellingtask.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case labellingtask.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case labellingtask.FieldInstructions:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstructions(v)
		return nil
	}
	return fmt.Errorf("unknown LabellingTask field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LabellingTaskMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LabellingTaskMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabellingTaskMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown LabellingTask numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LabellingTaskMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(labellingtask.FieldDescription) {
		fields = append(fields, labellingtask.FieldDescription)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LabellingTaskMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LabellingTaskMutation) ClearField(name string) error {
	switch name {
	case labellingtask.FieldDescription:
		m.ClearDescription()
		return nil
	}
	return fmt.Errorf("unknown LabellingTask nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LabellingTaskMutation) ResetField(name string) error {
	switch name {
	case labellingtask.FieldName:
		m.ResetName()
		return nil
	case labellingtask.FieldDescription:
		m.ResetDescription()
		return nil
	case labellingtask.FieldInstructions:
		m.ResetInstructions()
		return nil
	}
	return fmt.Errorf("unknown LabellingTask field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LabellingTaskMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LabellingTaskMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LabellingTaskMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LabellingTaskMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LabellingTaskMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LabellingTaskMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LabellingTaskMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown LabellingTask unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LabellingTaskMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown LabellingTask edge %s", name)
}

// LabellingTaskResponseMutation represents an operation that mutates the LabellingTaskResponse nodes in the graph.
type LabellingTaskResponseMutation struct {
	config
	op            Op
	typ           string
	id            *int
	response      *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*LabellingTaskResponse, error)
	predicates    []predicate.LabellingTaskResponse
}

var _ ent.Mutation = (*LabellingTaskResponseMutation)(nil)

// labellingtaskresponseOption allows management of the mutation configuration using functional options.
type labellingtaskresponseOption func(*LabellingTaskResponseMutation)

// newLabellingTaskResponseMutation creates new mutation for the LabellingTaskResponse entity.
func newLabellingTaskResponseMutation(c config, op Op, opts ...labellingtaskresponseOption) *LabellingTaskResponseMutation {
	m := &LabellingTaskResponseMutation{
		config:        c,
		op:            op,
		typ:           TypeLabellingTaskResponse,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLabellingTaskResponseID sets the ID field of the mutation.
func withLabellingTaskResponseID(id int) labellingtaskresponseOption {
	return func(m *LabellingTaskResponseMutation) {
		var (
			err   error
			once  sync.Once
			value *LabellingTaskResponse
		)
		m.oldValue = func(ctx context.Context) (*LabellingTaskResponse, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().LabellingTaskResponse.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLabellingTaskResponse sets the old LabellingTaskResponse of the mutation.
func withLabellingTaskResponse(node *LabellingTaskResponse) labellingtaskresponseOption {
	return func(m *LabellingTaskResponseMutation) {
		m.oldValue = func(context.Context) (*LabellingTaskResponse, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LabellingTaskResponseMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LabellingTaskResponseMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LabellingTaskResponseMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LabellingTaskResponseMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().LabellingTaskResponse.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetResponse sets the "response" field.
func (m *LabellingTaskResponseMutation) SetResponse(s string) {
	m.response = &s
}

// Response returns the value of the "response" field in the mutation.
func (m *LabellingTaskResponseMutation) Response() (r string, exists bool) {
	v := m.response
	if v == nil {
		return
	}
	return *v, true
}

// OldResponse returns the old "response" field's value of the LabellingTaskResponse entity.
// If the LabellingTaskResponse object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LabellingTaskResponseMutation) OldResponse(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponse is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponse requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponse: %w", err)
	}
	return oldValue.Response, nil
}

// ResetResponse resets all changes to the "response" field.
func (m *LabellingTaskResponseMutation) ResetResponse() {
	m.response = nil
}

// Where appends a list predicates to the LabellingTaskResponseMutation builder.
func (m *LabellingTaskResponseMutation) Where(ps ...predicate.LabellingTaskResponse) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LabellingTaskResponseMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LabellingTaskResponseMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.LabellingTaskResponse, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LabellingTaskResponseMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LabellingTaskResponseMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (LabellingTaskResponse).
func (m *LabellingTaskResponseMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LabellingTaskResponseMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.response != nil {
		fields = append(fields, labellingtaskresponse.FieldResponse)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LabellingTaskResponseMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case labellingtaskresponse.FieldResponse:
		return m.Response()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LabellingTaskResponseMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case labellingtaskresponse.FieldResponse:
		return m.OldResponse(ctx)
	}
	return nil, fmt.Errorf("unknown LabellingTaskResponse field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabellingTaskResponseMutation) SetField(name string, value ent.Value) error {
	switch name {
	case labellingtaskresponse.FieldResponse:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponse(v)
		return nil
	}
	return fmt.Errorf("unknown LabellingTaskResponse field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LabellingTaskResponseMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LabellingTaskResponseMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LabellingTaskResponseMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown LabellingTaskResponse numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LabellingTaskResponseMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LabellingTaskResponseMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LabellingTaskResponseMutation) ClearField(name string) error {
	return fmt.Errorf("unknown LabellingTaskResponse nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LabellingTaskResponseMutation) ResetField(name string) error {
	switch name {
	case labellingtaskresponse.FieldResponse:
		m.ResetResponse()
		return nil
	}
	return fmt.Errorf("unknown LabellingTaskResponse field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LabellingTaskResponseMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LabellingTaskResponseMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LabellingTaskResponseMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LabellingTaskResponseMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LabellingTaskResponseMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LabellingTaskResponseMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LabellingTaskResponseMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown LabellingTaskResponse unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LabellingTaskResponseMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown LabellingTaskResponse edge %s", name)
}

// QualificationMutation represents an operation that mutates the Qualification nodes in the graph.
type QualificationMutation struct {
	config
	op             Op
	typ            string
	id             *int
	value          *enums.QualificationValue
	clearedFields  map[string]struct{}
	experts        map[int]struct{}
	removedexperts map[int]struct{}
	clearedexperts bool
	done           bool
	oldValue       func(context.Context) (*Qualification, error)
	predicates     []predicate.Qualification
}

var _ ent.Mutation = (*QualificationMutation)(nil)

// qualificationOption allows management of the mutation configuration using functional options.
type qualificationOption func(*QualificationMutation)

// newQualificationMutation creates new mutation for the Qualification entity.
func newQualificationMutation(c config, op Op, opts ...qualificationOption) *QualificationMutation {
	m := &QualificationMutation{
		config:        c,
		op:            op,
		typ:           TypeQualification,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withQualificationID sets the ID field of the mutation.
func withQualificationID(id int) qualificationOption {
	return func(m *QualificationMutation) {
		var (
			err   error
			once  sync.Once
			value *Qualification
		)
		m.oldValue = func(ctx context.Context) (*Qualification, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Qualification.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withQualification sets the old Qualification of the mutation.
func withQualification(node *Qualification) qualificationOption {
	return func(m *QualificationMutation) {
		m.oldValue = func(context.Context) (*Qualification, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m QualificationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m QualificationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *QualificationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *QualificationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Qualification.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetValue sets the "value" field.
func (m *QualificationMutation) SetValue(ev enums.QualificationValue) {
	m.value = &ev
}

// Value returns the value of the "value" field in the mutation.
func (m *QualificationMutation) Value() (r enums.QualificationValue, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Qualification entity.
// If the Qualification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *QualificationMutation) OldValue(ctx context.Context) (v enums.QualificationValue, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// ResetValue resets all changes to the "value" field.
func (m *QualificationMutation) ResetValue() {
	m.value = nil
}

// AddExpertIDs adds the "experts" edge to the Expert entity by ids.
func (m *QualificationMutation) AddExpertIDs(ids ...int) {
	if m.experts == nil {
		m.experts = make(map[int]struct{})
	}
	for i := range ids {
		m.experts[ids[i]] = struct{}{}
	}
}

// ClearExperts clears the "experts" edge to the Expert entity.
func (m *QualificationMutation) ClearExperts() {
	m.clearedexperts = true
}

// ExpertsCleared reports if the "experts" edge to the Expert entity was cleared.
func (m *QualificationMutation) ExpertsCleared() bool {
	return m.clearedexperts
}

// RemoveExpertIDs removes the "experts" edge to the Expert entity by IDs.
func (m *QualificationMutation) RemoveExpertIDs(ids ...int) {
	if m.removedexperts == nil {
		m.removedexperts = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.experts, ids[i])
		m.removedexperts[ids[i]] = struct{}{}
	}
}

// RemovedExperts returns the removed IDs of the "experts" edge to the Expert entity.
func (m *QualificationMutation) RemovedExpertsIDs() (ids []int) {
	for id := range m.removedexperts {
		ids = append(ids, id)
	}
	return
}

// ExpertsIDs returns the "experts" edge IDs in the mutation.
func (m *QualificationMutation) ExpertsIDs() (ids []int) {
	for id := range m.experts {
		ids = append(ids, id)
	}
	return
}

// ResetExperts resets all changes to the "experts" edge.
func (m *QualificationMutation) ResetExperts() {
	m.experts = nil
	m.clearedexperts = false
	m.removedexperts = nil
}

// Where appends a list predicates to the QualificationMutation builder.
func (m *QualificationMutation) Where(ps ...predicate.Qualification) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the QualificationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *QualificationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Qualification, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *QualificationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *QualificationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Qualification).
func (m *QualificationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *QualificationMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.value != nil {
		fields = append(fields, qualification.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *QualificationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case qualification.FieldValue:
		return m.Value()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *QualificationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case qualification.FieldValue:
		return m.OldValue(ctx)
	}
	return nil, fmt.Errorf("unknown Qualification field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *QualificationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case qualification.FieldValue:
		v, ok := value.(enums.QualificationValue)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Qualification field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *QualificationMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *QualificationMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *QualificationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Qualification numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *QualificationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *QualificationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *QualificationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Qualification nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *QualificationMutation) ResetField(name string) error {
	switch name {
	case qualification.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Qualification field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *QualificationMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.experts != nil {
		edges = append(edges, qualification.EdgeExperts)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *QualificationMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case qualification.EdgeExperts:
		ids := make([]ent.Value, 0, len(m.experts))
		for id := range m.experts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *QualificationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedexperts != nil {
		edges = append(edges, qualification.EdgeExperts)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *QualificationMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case qualification.EdgeExperts:
		ids := make([]ent.Value, 0, len(m.removedexperts))
		for id := range m.removedexperts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *QualificationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedexperts {
		edges = append(edges, qualification.EdgeExperts)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *QualificationMutation) EdgeCleared(name string) bool {
	switch name {
	case qualification.EdgeExperts:
		return m.clearedexperts
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *QualificationMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Qualification unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *QualificationMutation) ResetEdge(name string) error {
	switch name {
	case qualification.EdgeExperts:
		m.ResetExperts()
		return nil
	}
	return fmt.Errorf("unknown Qualification edge %s", name)
}
