// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/carlosruizg/muni/ent/qualification"
	"github.com/carlosruizg/muni/enums"
)

// Qualification is the model entity for the Qualification schema.
type Qualification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Value holds the value of the "value" field.
	Value enums.QualificationValue `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QualificationQuery when eager-loading is set.
	Edges        QualificationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// QualificationEdges holds the relations/edges for other nodes in the graph.
type QualificationEdges struct {
	// Experts holds the value of the experts edge.
	Experts []*Expert `json:"experts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedExperts map[string][]*Expert
}

// ExpertsOrErr returns the Experts value or an error if the edge
// was not loaded in eager-loading.
func (e QualificationEdges) ExpertsOrErr() ([]*Expert, error) {
	if e.loadedTypes[0] {
		return e.Experts, nil
	}
	return nil, &NotLoadedError{edge: "experts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Qualification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case qualification.FieldID:
			values[i] = new(sql.NullInt64)
		case qualification.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Qualification fields.
func (q *Qualification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case qualification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			q.ID = int(value.Int64)
		case qualification.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				q.Value = enums.QualificationValue(value.String)
			}
		default:
			q.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the Qualification.
// This includes values selected through modifiers, order, etc.
func (q *Qualification) GetValue(name string) (ent.Value, error) {
	return q.selectValues.Get(name)
}

// QueryExperts queries the "experts" edge of the Qualification entity.
func (q *Qualification) QueryExperts() *ExpertQuery {
	return NewQualificationClient(q.config).QueryExperts(q)
}

// Update returns a builder for updating this Qualification.
// Note that you need to call Qualification.Unwrap() before calling this method if this Qualification
// was returned from a transaction, and the transaction was committed or rolled back.
func (q *Qualification) Update() *QualificationUpdateOne {
	return NewQualificationClient(q.config).UpdateOne(q)
}

// Unwrap unwraps the Qualification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (q *Qualification) Unwrap() *Qualification {
	_tx, ok := q.config.driver.(*txDriver)
	if !ok {
		panic("ent: Qualification is not a transactional entity")
	}
	q.config.driver = _tx.drv
	return q
}

// String implements the fmt.Stringer.
func (q *Qualification) String() string {
	var builder strings.Builder
	builder.WriteString("Qualification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", q.ID))
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", q.Value))
	builder.WriteByte(')')
	return builder.String()
}

// NamedExperts returns the Experts named value or an error if the edge was not
// loaded in eager-loading with this name.
func (q *Qualification) NamedExperts(name string) ([]*Expert, error) {
	if q.Edges.namedExperts == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := q.Edges.namedExperts[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (q *Qualification) appendNamedExperts(name string, edges ...*Expert) {
	if q.Edges.namedExperts == nil {
		q.Edges.namedExperts = make(map[string][]*Expert)
	}
	if len(edges) == 0 {
		q.Edges.namedExperts[name] = []*Expert{}
	} else {
		q.Edges.namedExperts[name] = append(q.Edges.namedExperts[name], edges...)
	}
}

// Qualifications is a parsable slice of Qualification.
type Qualifications []*Qualification
