// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/carlosruizg/muni/ent/expert"
	"github.com/carlosruizg/muni/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	expertFields := schema.Expert{}.Fields()
	_ = expertFields
	// expertDescName is the schema descriptor for name field.
	expertDescName := expertFields[0].Descriptor()
	// expert.NameValidator is a validator for the "name" field. It is called by the builders before save.
	expert.NameValidator = expertDescName.Validators[0].(func(string) error)
}
