// Code generated by ent, DO NOT EDIT.

package labellingtask

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the labellingtask type in the database.
	Label = "labelling_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldInstructions holds the string denoting the instructions field in the database.
	FieldInstructions = "instructions"
	// Table holds the table name of the labellingtask in the database.
	Table = "labelling_tasks"
)

// Columns holds all SQL columns for labellingtask fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldInstructions,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the LabellingTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByInstructions orders the results by the instructions field.
func ByInstructions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstructions, opts...).ToFunc()
}
