// Code generated by ent, DO NOT EDIT.

package labellingtaskresponse

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the labellingtaskresponse type in the database.
	Label = "labelling_task_response"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResponse holds the string denoting the response field in the database.
	FieldResponse = "response"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// EdgeExpert holds the string denoting the expert edge name in mutations.
	EdgeExpert = "expert"
	// Table holds the table name of the labellingtaskresponse in the database.
	Table = "labelling_task_responses"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "labelling_task_responses"
	// TaskInverseTable is the table name for the LabellingTask entity.
	// It exists in this package in order to avoid circular dependency with the "labellingtask" package.
	TaskInverseTable = "labelling_tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "labelling_task_responses"
	// ExpertTable is the table that holds the expert relation/edge.
	ExpertTable = "labelling_task_responses"
	// ExpertInverseTable is the table name for the Expert entity.
	// It exists in this package in order to avoid circular dependency with the "expert" package.
	ExpertInverseTable = "experts"
	// ExpertColumn is the table column denoting the expert relation/edge.
	ExpertColumn = "expert_task_responses"
)

// Columns holds all SQL columns for labellingtaskresponse fields.
var Columns = []string{
	FieldID,
	FieldResponse,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "labelling_task_responses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"expert_task_responses",
	"labelling_task_responses",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the LabellingTaskResponse queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResponse orders the results by the response field.
func ByResponse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponse, opts...).ToFunc()
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}

// ByExpertField orders the results by expert field.
func ByExpertField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExpertStep(), sql.OrderByField(field, opts...))
	}
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
	)
}
func newExpertStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExpertInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExpertTable, ExpertColumn),
	)
}
