// Code generated by ent, DO NOT EDIT.

package labellingtaskresponse

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/carlosruizg/muni/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldLTE(FieldID, id))
}

// Response applies equality check predicate on the "response" field. It's identical to ResponseEQ.
func Response(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldEQ(FieldResponse, v))
}

// ResponseEQ applies the EQ predicate on the "response" field.
func ResponseEQ(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldEQ(FieldResponse, v))
}

// ResponseNEQ applies the NEQ predicate on the "response" field.
func ResponseNEQ(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldNEQ(FieldResponse, v))
}

// ResponseIn applies the In predicate on the "response" field.
func ResponseIn(vs ...string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldIn(FieldResponse, vs...))
}

// ResponseNotIn applies the NotIn predicate on the "response" field.
func ResponseNotIn(vs ...string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldNotIn(FieldResponse, vs...))
}

// ResponseGT applies the GT predicate on the "response" field.
func ResponseGT(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldGT(FieldResponse, v))
}

// ResponseGTE applies the GTE predicate on the "response" field.
func ResponseGTE(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldGTE(FieldResponse, v))
}

// ResponseLT applies the LT predicate on the "response" field.
func ResponseLT(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldLT(FieldResponse, v))
}

// ResponseLTE applies the LTE predicate on the "response" field.
func ResponseLTE(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldLTE(FieldResponse, v))
}

// ResponseContains applies the Contains predicate on the "response" field.
func ResponseContains(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldContains(FieldResponse, v))
}

// ResponseHasPrefix applies the HasPrefix predicate on the "response" field.
func ResponseHasPrefix(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldHasPrefix(FieldResponse, v))
}

// ResponseHasSuffix applies the HasSuffix predicate on the "response" field.
func ResponseHasSuffix(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldHasSuffix(FieldResponse, v))
}

// ResponseEqualFold applies the EqualFold predicate on the "response" field.
func ResponseEqualFold(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldEqualFold(FieldResponse, v))
}

// ResponseContainsFold applies the ContainsFold predicate on the "response" field.
func ResponseContainsFold(v string) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(sql.FieldContainsFold(FieldResponse, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.LabellingTask) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExpert applies the HasEdge predicate on the "expert" edge.
func HasExpert() predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExpertTable, ExpertColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExpertWith applies the HasEdge predicate on the "expert" edge with a given conditions (other predicates).
func HasExpertWith(preds ...predicate.Expert) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(func(s *sql.Selector) {
		step := newExpertStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LabellingTaskResponse) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LabellingTaskResponse) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LabellingTaskResponse) predicate.LabellingTaskResponse {
	return predicate.LabellingTaskResponse(func(s *sql.Selector) {
		p(s.Not())
	})
}
